# Generated by Django 3.0.2 on 2020-01-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0003_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(),
        ),
    ]
