# Generated by Django 3.0.2 on 2020-01-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0006_auto_20200124_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='commited',
            field=models.BooleanField(default=False),
        ),
    ]
