# Generated by Django 3.0.2 on 2020-02-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0008_post_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='hero_images/'),
        ),
    ]
