# Generated by Django 3.0.2 on 2020-02-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0009_auto_20200206_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='hero_image',
            new_name='card_image',
        ),
        migrations.AddField(
            model_name='post',
            name='card_description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
